### ISSUE TITLE
Sharing code of experiments with RoBERTa, Presidio, and Longformer

### ISSUE THREAD

**Issue by msierrofer** [NorskRegnesentral/text-anonymization-benchmark#5]
Hello!
I have recently read your paper and I found your work very interesting.
In fact, I might use it as a basis for building a corpus of legal texts in French and Spanish language for anonymization.
Thank you for having shared the annotated corpus as well as the code for evaluation.
Would it be possible to also share the code that you used in your anonymization experiments with RoBERTa language model, Presidio, and fine-tuned Longformer? It would be awesome :)
I would like to be able to replicate your experiments before starting to make my own.

**Comment by anthipapa** [comment]
Hi and thank you for your interest!
Of course, I'm currently working on this, and will upload the relevant code soon! :)

**Comment by msierrofer** [comment]
That's great, thank you very much!
